apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q296mbp51-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/q296mbp51-java-springboot-gitops